{
 "title": "EB .NET Sample",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "awsregion", "label": "AWSRegion", "query": "regions()" },
   {
    "name": "customerid",
    "label": "CustomerID",
    "query": "ec2_instance_attribute($awsregion,Tags.CustomerID,{})"
   },
   {
    "name": "env",
    "label": "Env",
    "query": "ec2_instance_attribute($awsregion,Tags.Env,{\"tag:CustomerID\":[\"$customerid\"]})"
   },
   {
    "name": "appname",
    "label": "AppName",
    "query": "ec2_instance_attribute($awsregion,Tags.AppName,{\"tag:CustomerID\":[\"$customerid\"],\"tag:Env\":[\"$env\"]})"
   },
   {
    "name": "fs_name",
    "label": "FSName",
    "query": "ec2_instance_attribute($awsregion,Tags.AppName,{\"tag:CustomerID\":[\"$customerid\"],\"tag:Env\":[\"$env\"]})"
   },
   {
    "name": "rdslist",
    "label": "RDSList",
    "query": "resource_arns($awsregion,rds:db,{\"CustomerID\":[\"$customerid\"],\"Env\":[\"$env\"]})"
   },
   {
    "name": "app_pools_cpu",
    "label": "App_Pools_CPU",
    "query": "dimension_values($awsregion,EBSampleApp,procstat cpu_usage,application_pool_name)"
   },
   {
    "name": "app_pools_mem",
    "label": "App_Pools_Mem",
    "query": "dimension_values($awsregion,EBSampleApp,procstat memory_rss,application_pool_name)"
   },
   {
    "name": "ec2list_app",
    "label": "EC2List_App",
    "query": "ec2_instance_attribute($awsregion,InstanceId,{\"tag:CustomerID\":[\"$customerid\"],\"tag:Env\":[\"$env\"],\"tag:AppName\":[\"$appname\"]})"
   },
   {
    "name": "ec2list_filesrv",
    "label": "EC2List_FileSrv",
    "query": "ec2_instance_attribute($awsregion,InstanceId,{\"tag:CustomerID\":[\"$customerid\"],\"tag:Env\":[\"$env\"],\"tag:AppName\":[\"$fs_name\"]})"
   },
   {
    "name": "alblist",
    "label": "ALBList",
    "query": "resource_arns($awsregion,elasticloadbalancing:loadbalancer,{\"CustomerID\":[\"$customerid\"],\"Env\":[\"$env\"]})"
   }
  ]
 },
 "panels": [
  { "title": "ELB Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP 5XX Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{LoadBalancer}}",
     "dimensions": { "LoadBalancer": "$alblist" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Target Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{LoadBalancer}}",
     "dimensions": { "LoadBalancer": "$alblist" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "EC2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}} - app server",
     "dimensions": { "InstanceId": "$ec2list_app" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{InstanceId}} - file server",
     "dimensions": { "InstanceId": "$ec2list_filesrv" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ASP.NET Requests Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$ec2list_app" },
     "metricName": "ASP.NET Requests Current",
     "namespace": "EBSampleApp",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "App Pool CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}} {{application_pool_name}}",
     "dimensions": {
      "InstanceId": "$ec2list_app",
      "application_pool_name": "$app_pools_cpu",
      "process_name": "w3wp.exe"
     },
     "metricName": "procstat cpu_usage",
     "namespace": "EBSampleApp",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "App Pool Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}} {{application_pool_name}}",
     "dimensions": {
      "InstanceId": "$ec2list_app",
      "application_pool_name": "$app_pools_mem",
      "process_name": "w3wp.exe"
     },
     "metricName": "procstat memory_rss",
     "namespace": "EBSampleApp",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "RDS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$rdslist" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$rdslist" },
     "metricName": "ClientConnections",
     "namespace": "AWS/RDS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}